### ISSUE TITLE
resize disk

### ISSUE THREAD

**Issue by emper0r** [mrlesmithjr/ansible-manage-lvm#42] opened 2020-04-27 13:18 UTC
Hi, 

Days ago the module works fine... today I pulled from repo to get updates and now get this error

my config
###     lvm vars
manage_lvm: true
lvm_disk_mount: "/dockerlvm/docker"
lvm_groups:
  - vgname: 'docker'
    disks:
      - /dev/sdb
    create: true
    lvnames:
      - lvname: 'docker'
        size: 169.95g                <--- I just grow the disk so I'm increasing other 40gb from 129.5
        create: true
        filesystem: ext4
        mount: true
        mntp: "{{ lvm_disk_mount }}"

I Increase vmware disk
did partprobe
did pvresize /dev/sdb2 as always did before lunch the deploy.

error found

TASK [ext-mrlesmithjr.manage-lvm : centos | install xfs tools] **************************************************************************************************************************************
Monday 27 April 2020  15:13:34 +0200 (0:00:00.093)       0:00:59.796 **********
fatal: [docker2]: FAILED! =>
  msg: 'Invalid data passed to ''loop'', it requires a list, got this instead: ({u''vgname'': u''docker'', u''disks'': [u''/dev/sdb''], u''create'': True}, {u''lvname'': u''docker'', u''create'': True, u''filesystem'': u''ext4'', u''mntp'': u''/dockerlvm/docker'', u''mount'': True, u''size'': u''169.95g''}). Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup.'

PLAY RECAP ******************************************************************************************************************************************************************************************
docker2                    : ok=4    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0

**Comment by mrlesmithjr** [comment] 2020-04-27 15:59
@emper0r Thanks for raising this issue. The fix has been put into place and **SHOULD** resolve your issue. Please pull the latest code and let us know if the issue is resolved for you.

**Comment by emper0r** [comment] 2020-04-27 16:29
Hi, thanks for your quick push..
I pulled and received the change but still doesn't work,
![image](https://user-images.githubusercontent.com/819042/80396461-f68abe00-88b4-11ea-8e7a-ef70ca2c9de3.png)

**Comment by mrlesmithjr** [comment] 2020-04-27 17:36
@emper0r Fix will be available here shortly! Hope this gets the issue resolved.

**Closed as completed** 2020-04-27 17:41 UTC

**Comment by mrlesmithjr** [comment] 2020-04-27 17:42
@emper0r Fix has been tested using your provided vars and seems to be good to go now.

**Comment by emper0r** [comment] 2020-04-28 07:29
Hi @mrlesmithjr , just for update!.. 
Thanks for the fix.. now works!.. great job! 👍
Have a nice day
